apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-service
    app: app
  name: app
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: app
status:
  loadBalancer: {}
