apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.service: api
  name: api
spec:
  replicas: 4
  selector:
    matchLabels:
      app.service: api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.network/app-net: "true"
        app.service: api
    spec:
      containers:
        - image: ankit123nagarro/api
          name: api
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
