apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
  name: app-net
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              network/app-net: "true"
  podSelector:
    matchLabels:
      network/app-net: "true"
