apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "ConStr": "Server=db;Database=master;User=sa;Password=Your_password123;" 
      } 
    }
