apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f D:\NAGP\Kubernetes\Solution\kubernetes\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    app.service: app
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.service: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.network/app-net: "true"
        app.service: app
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: ankit123nagarro/app
          name: app
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
