apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.service: app
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.service: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.network/app-net: "true"
        app.service: app
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: appconfig
                  key: env
            - name: REACT_APP_API
              valueFrom:
                configMapKeyRef:
                  name: appconfig
                  key: api-url
          image: ankit123nagarro/app
          name: app
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
