apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.service: db
  name: db
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    app.service: db
status:
  loadBalancer: {}
