apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    service: db
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    service: db
status:
  loadBalancer: {}
